development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: db/storyteller_rails_v2_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: db/storyteller_rails_v2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: db/storyteller_rails_v2
  pool: 5
  timeout: 5000
